CookMe/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
     path("", include("LaDispensa.urls")),
]

LaDispensa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.landing, name="landing"),
    path("index", views.index, name="index"),
    path("submit", views.submit_recipe, name="submit-recipe"),
    path("test-kitchen/<int:recipe_id>", views.test_kitchen, name="test-kitchen"),

    # API routes
    path("recipes", views.recipes, name="get_recipes"),
    path("recipes/<int:recipe_id>", views.recipe, name="recipe"),
]

LaDispensa/models.py
from django.contrib.auth.models import AbstractUser
from django.utils import timezone
from django.db import models
import json
import re

DELIMITER = '|||'

class User(AbstractUser):
    pass

class Ingredient(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    
class PantryIngredient(models.Model):
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField()

class AbstractRecipe(models.Model):
    title = models.CharField(max_length=50)
    instructions = models.TextField()
    time = models.IntegerField()
    created_on = models.DateTimeField(blank=True, default=timezone.now)

    def get_instructions(self):
        return self.instructions.split(DELIMITER) if self.instructions else []

class Recipe(AbstractRecipe):
    img = models.ImageField(blank=True, upload_to='LaDispensa/static/ladispensa/imgs/recipes')

    def set_instructions(self, instructions_list):
        self.instructions = DELIMITER.join(instructions_list)

    def log_history(self):
        old_recipe = RecipeHistory(
            current=self,
            title=self.title,
            ingredients= json.dumps(
                [ingredient.serialize() for ingredient in self.ingredients.all()]
                ),
            instructions=self.instructions,
            time=self.time,
        )
        old_recipe.save()
        self.history.add(old_recipe)
        self.save()

    def serialize(self):
        return {
            "id": self.id,
            "ingredients": [ingredient.serialize() for ingredient in self.ingredients.all()],
            "title": self.title,
            "time": self.time,
            "instructions": [{
                "count": count,
                "text": text,
            } for count,text in enumerate(self.instructions.split(DELIMITER),1)],
            "img": self.img.url[12:] if self.img else None,
            "created": self.created_on,
            "history": [recipe.serialize() for recipe in self.history.all().order_by("-created_on")],
        }

    
class RecipeHistory(AbstractRecipe):
    current = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='history')
    ingredients = models.TextField()

    def serialize(self):
        return {
            "id": self.id,
            "ingredients": json.loads(self.ingredients),
            "title": self.title,
            "time": self.time,
            "instructions": [{
                "count": count,
                "text": text,
            } for count,text in enumerate(self.instructions.split(DELIMITER),1)],
            "created": self.created_on,
        }

class RecipeIngredient(models.Model):
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name='ingredients')
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    quantity = models.FloatField()
    unit = models.CharField(max_length=10)

    def serialize(self):
        return {
            "ingredient":self.ingredient.name,
            "quantity":self.quantity,
            "unit":self.unit,
        }

    def __str__(self):
        return f'{self.quantity}{self.unit} of {self.item}'

LaDispensa/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.db.models import Q
from django.urls import reverse
from django import forms
import re
from django.views.decorators.csrf import csrf_exempt
import json

from .models import User, Recipe, Ingredient, RecipeIngredient

CHOICES = (
    ('', ''),
    ('g', 'g'),
    ('unit(s)', 'unit(s)'),
    ('kg', 'kg'),
    ('ml', 'ml'),
    ('L', 'L'),
    ('tsp', 'tsp'),
    ('tbsp', 'tbsp'),
    ('cup(s)', 'cup(s)'),
)

class RecipeForm(forms.Form,):
    def __init__(self, *args, **kwargs):
        num_instruction = kwargs.pop('num_instructions')
        num_ingredients = kwargs.pop('num_ingredients')
        super(RecipeForm, self).__init__(*args, **kwargs)

        counter = 1
        for _ in range(num_instruction):
            self.fields['instruction_' + str(counter)] = forms.CharField()
            counter += 1

        counter = 1
        for _ in range(num_ingredients):
            self.fields['ingredient_' + str(counter)] = forms.CharField()
            self.fields['quantity_' + str(counter)] = forms.IntegerField()
            self.fields['unit_' + str(counter)] = forms.ChoiceField(choices = CHOICES)
            counter += 1

        for visible, fieldname in zip(self.visible_fields(),self.fields):
            if fieldname != 'image':
                visible.field.widget.attrs['class'] = 'form__field'
                visible.field.widget.attrs['name'] = 'input'
                visible.field.widget.attrs['autocomplete'] = 'off'

    def get_instruction_fields(self):
        c = 0
        for field_name in self.fields:
            if field_name.startswith('instruction_'):
                c += 1
                yield c, self[field_name]

    def get_ingredient_fields(self):
        for field_name in self.fields:
            if field_name.startswith('ingredient_'):
                m = re.search(r'\d+$',field_name)
                i = int(m.group()) if m else None
                yield self[field_name], self[f'quantity_{i}'], self[f'unit_{i}']

    title = forms.CharField()
    time = forms.IntegerField()
    image = forms.ImageField(required=False)


def landing(request):
    return render(request, "ladispensa/landing.html")


def index(request):
    return render(request, "ladispensa/index.html", {
        'form': RecipeForm(num_ingredients=3,num_instructions=3)
    })


@csrf_exempt
def recipe(request, recipe_id):
    if request.method == "DELETE":
        Recipe.objects.get(pk=recipe_id).delete()
        return JsonResponse({"message": "Recipe deleted Succesfully."}, status=200)

    if request.method == "GET":
        data = Recipe.objects.get(pk=recipe_id)
        return JsonResponse({
            'recipe': data.serialize()
            })


def recipes(request):
    start = int(request.GET.get("start") or 0)
    end = int(request.GET.get("end") or (start + 9))

    if request.GET.get("title"):
        condition = Q(title__icontains=request.GET.get("title"))
        data = Recipe.objects.filter(condition)
    else:
        data = Recipe.objects.all()

    end = min(end,len(data))
    
    return JsonResponse({
        "posts": [recipe.serialize() for recipe in data[start:end]],
    })


def submit_recipe(request):
    if request.method == "POST":

        items = request.POST.items()
        instructions = [value for key, value in items if re.compile(r'instruction_[0-9]').match(key)]

        ingredients = [value for key, value in request.POST.items() if 
                      re.compile(r'ingredient_[0-9]').match(key)]
        quantities = [value for key, value in request.POST.items() if 
                      re.compile(r'quantity_[0-9]').match(key)]
        units = [value for key, value in request.POST.items() if 
                      re.compile(r'unit_[0-9]').match(key)]
        form = RecipeForm(request.POST,
                          request.FILES,
                          num_instructions=len(instructions),
                          num_ingredients=len(ingredients)
                          )

        if form.is_valid():
            recipe = Recipe.objects.create(
                title=form.cleaned_data["title"],
                time=form.cleaned_data["time"],
            )
            if form.cleaned_data["image"]:
                recipe.img = form.cleaned_data["image"]
            recipe.set_instructions(instructions)
            recipe.save()

            for i,q,u in zip(ingredients,quantities,units):
                if Ingredient.objects.filter(name=i).exists():
                    ingredient = Ingredient.objects.get(name=i)
                else:
                    ingredient = Ingredient(name=i)
                    ingredient.save()

                recipe_ingredient = RecipeIngredient(
                    ingredient=ingredient,
                    recipe=recipe,
                    quantity=q,
                    unit=u,
                )
                recipe_ingredient.save()
                recipe.ingredients.add(recipe_ingredient)
            
            recipe.save()

        return HttpResponseRedirect(reverse("index"))
    return HttpResponseRedirect(reverse("index"))


@csrf_exempt
def test_kitchen(request, recipe_id):
    if request.method == "GET":
        recipe = Recipe.objects.get(pk=recipe_id)
        return render(request, "ladispensa/test_kitchen.html",{
            'recipe': recipe.serialize(),
            'form': RecipeForm(num_ingredients=1,num_instructions=1),
        })
    
    elif request.method == "PUT":
        recipe = Recipe.objects.get(pk=recipe_id)
        recipe.log_history()
        data = json.loads(request.body)
        recipe.set_instructions(data['instructions'])

        for i,q,u in zip(data['ingredients'],data['quantities'],data['units']):
            if Ingredient.objects.filter(name=i).exists():
                    ingredient = Ingredient.objects.get(name=i)
            else:
                ingredient = Ingredient(name=i)
                ingredient.save()
            
            if RecipeIngredient.objects.filter(
                ingredient=ingredient,
                recipe=recipe,
                quantity=q,
                unit=u,
            ).exists():
                continue
            elif RecipeIngredient.objects.filter(
                ingredient=ingredient,
                recipe=recipe,
            ).exists():
                recipe_ingredient = RecipeIngredient.objects.get(ingredient=ingredient,
                                                                 recipe=recipe,)
                recipe.ingredients.remove(recipe_ingredient)

            recipe_ingredient = RecipeIngredient(
                ingredient=ingredient,
                recipe=recipe,
                quantity=q,
                unit=u,
            )
            recipe_ingredient.save()

            recipe.ingredients.add(recipe_ingredient)

        recipe.save()

        return JsonResponse({
        "message": "post updated successfully",
    }, status=201)

LaDispensa/templates/ladispensa/index.html
{% extends "ladispensa/layout.html" %}
{% load static %}

{% block body %}
<div class="form__container">
    <div id="add-recipe-header">
        <div id="add-recipe-title">
            Upload Recipe
        </div>
        <img src="{% static 'ladispensa/imgs/index/arrow-down.svg' %}">
        <img class="hidden" src="{% static 'ladispensa/imgs/index/arrow-up.svg' %}">
    </div>
    <form class="add-recipe-body" action="{% url 'submit-recipe' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <div class="form__group field" id="form__title">
                {{ form.title }}
                <label for="id_title" class="form__label">Title</label>
            </div>
            <div class="form__group field" id="form__time">
                {{ form.time }}
                <label for="id_time" class="form__label">Time</label>
            </div>
        </div>
        <div class="form-ingredients">
            {% for ingredient, quantity, unit in form.get_ingredient_fields %}
            <div class="form-ingredients__wrapper">
                {{ ingredient }}
                {{ quantity }}
                {{ unit }}
            </div>
            {% endfor %}
        </div>
        <div class="add-form-container">
            <img src="{% static 'ladispensa/imgs/index/add.svg' %}" id="add-ingredient">
            <img src="{% static 'ladispensa/imgs/index/subtract.svg' %}" id="rmv-ingredient">
        </div>
        <div class="form-instructions">
            {% for num, field in form.get_instruction_fields %}
            <div>
                <div>
                    {{ num }}.
                </div>
                {% if num == 1 %}
                <div class="form__group field" id="form__instructions">
                    {{ field }}
                    <label for="id_instruction_1" class="form__label">Instructions</label>
                </div>
                {% else %}
                {{ field }}
                {% endif %}
            </div>
            {% endfor %}
        </div>
        <div class="add-form-container">
            <img src="{% static 'ladispensa/imgs/index/add.svg' %}" id="add-instruction">
            <img src="{% static 'ladispensa/imgs/index/subtract.svg' %}" id="rmv-instruction">
        </div>
        <p>
            {{ form.image }}
        </p>
        <input type="submit" class="btn btn-primary" value="save">
    </form>
</div>



<div class="grid__container">
    <div class="form__group field">
        <input autocomplete="off" type="input" class="form__field" placeholder="Search" name="search" id='search' required />
        <label for="search" class="form__label">Search</label>
    </div>
    <div id="recipe-catalogue">
        <div class="hidden recipe-element">
            <img src="{% static 'ladispensa/imgs/index/tile.svg' %}">
            <div class="recipe-element__title"></div>
        </div>
    </div>
</div>



<div class="recipe__container hidden">
    <div class="recipe-header__wrapper"><h1></h1></div>
    <div class="recipe-focus spaced">
        <div class="recipe-image__wrapper"><img src=""></div>
        <div class="recipe-information__container">
            <div class="cook-time__wrapper">
                Time to Cook: <span class="cook-time"></span> mins
            </div>
        </div>
        <div class="recipe-actions__container">
            <img id="recipe-icons__back" src="{% static 'ladispensa/imgs/recipe/back.svg' %}">
            <img id="recipe-icons__cook" src="{% static 'ladispensa/imgs/recipe/cook.svg' %}">
            <a href="{% url 'test-kitchen' 0 %}" id="recipe-icons__edit">
                <img src="{% static 'ladispensa/imgs/recipe/edit.svg' %}">
            </a>
            <img id="recipe-icons__del" src="{% static 'ladispensa/imgs/recipe/delete.svg' %}">
        </div>
    </div>
    <div class="recipe-body">
        <div class="recipe-ingredient__container">
            <h2>Ingredients</h2>
            <div class="recipe-ingredient__wrapper hidden">
                <hr>
                <span class="recipe-quantity"></span>
                <span class="recipe-unit"></span>
                <span class="recipe-ingredient"></span>
            </div>
        </div>
        <div class="recipe-instruction__container">
            <h2>Method</h2>
            <div class="recipe-instruction__wrapper spaced hidden">
                STEP <span class="recipe-instruction-count"></span><br>
                <span class="recipe-instruction-text"></span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block stylesheet %}
<link href="{% static 'ladispensa/styles/css/index.css' %}" rel="stylesheet">
<link href="{% static 'ladispensa/styles/css/recipe.css' %}" rel="stylesheet">
<link href="{% static 'ladispensa/styles/css/forms.css' %}" rel="stylesheet">
{% endblock %}

{% block script %}
<script src="{% static 'ladispensa/javascript/index.js' %}"></script>
<script src="{% static 'ladispensa/javascript/recipe.js' %}"></script>
{% endblock %}

LaDispensa/templates/ladispensa/landing.html
{% extends "ladispensa/layout.html" %}
{% load static %}

{% block body %}
<img src="{% static 'ladispensa/imgs/background/VectorLanding.png' %}">
<img src="{% static 'ladispensa/imgs/background/NoiseLanding.png' %}">
<div id="landing__main">
    <div id="landing__title">La Dispensa</div>
    <div id="landing__subtitle">by Max Marvell</div>
</div>
{% endblock %}

{% block stylesheet %}
<link href="{% static 'ladispensa/styles/css/landing.css' %}" rel="stylesheet" height="656" width="742">
{% endblock %}

LaDispensa/templates/ladispensa/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}La Dispensa{% endblock %}</title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Tulpen+One&display=swap" rel="stylesheet">
        {% block stylesheet %}
        {% endblock %}
        <link href="{% static 'ladispensa/styles/css/layout.css' %}" rel="stylesheet">
        <script src="{% static 'ladispensa/javascript/layout.js' %}"></script>
        {% block script %}
        {% endblock %}
    </head>
    <body>
        <div id="menu-select">
            <div id="menu-select__closed">
                <img src="{% static 'ladispensa/imgs/menu/Polygon 1menu__closed.svg' %}">
                <img id="menu-select__decorator" src="{% static 'ladispensa/imgs/menu/Unionmenu__closed.svg' %}">
            </div>
            <div id="menu-select__open">
                <img src="{% static 'ladispensa/imgs/menu/menu-open.svg' %}">
                <div>
                    <img id="menu-select__decorator" src="{% static 'ladispensa/imgs/menu/back-arrow.svg' %}">
                    <a href="{% url 'index' %}">Recipes</a>
                    <a>Test Kitchen</a>
                    <a>Pantry</a>
                    <a>Login</a>
                    <a href="{% url 'landing' %}">Home</a>
                </div>
            </div>
        </div>
        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

LaDispensa/templates/ladispensa/test_kitchen.html
{% extends "ladispensa/layout.html" %}
{% load static %}

{% block body %}
<h1>Test Kitchen</h1>
<select type="input" class="form__field" placeholder="Search" name="search" id='search' required></select>
{% if recipe %}
<div class="test-kitchen__container">
    <hr>
    <h1 id="{{ recipe.id }}" class="recipe-title"></h1>
    <div>
        <h1>original</h1>
        <div class="recipe-ticket__container">
            <div class="recipe-ticket staged-iteration">
                <div class="ticket-date">
                    Dated: 
                </div>
                <div class="ticket-ingredient__container">
                    <div class="ticket-ingredient__wrapper">
                        <span class="recipe-quantity"></span>
                        <span class="recipe-unit"></span>
                        <span class="recipe-ingredient"></span>
                    </div>
                </div>
                <div class="ticket-instruction__container">
                    <div class="ticket-instruction__wrapper">
                        STEP <span class="recipe-instruction-count"></span><br>
                        <span class="recipe-instruction-text"></span>
                    </div>
                </div>
            </div>
            <div class="tag__container">
                <div class="slideouts__container">
                    <div class="slideout">
                        <div class="notes__container">
                            <div class="slideout__header">
                                Notes.
                                <img id="close-slideout" src="{% static 'ladispensa/imgs/edit--recipe/cross.svg' %}">
                            </div>
                        </div>
                    </div>
                    <div class="slideout">
                        <form class="update-recipe" action="{% url 'submit-recipe' %}" method="put">
                            {% csrf_token %}
                            <div class="slideout__header">
                                Edit.
                                <img id="close-slideout" src="{% static 'ladispensa/imgs/edit--recipe/cross.svg' %}">
                            </div>
                            <div class="form-ingredients">
                                {% for ingredient, quantity, unit in form.get_ingredient_fields %}
                                <div class="form-ingredients__wrapper">
                                    {{ ingredient }}
                                    {{ quantity }}
                                    {{ unit }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="add-form-container">
                                <img src="{% static 'ladispensa/imgs/index/add.svg' %}"
                                width="15" height="15" id="add-ingredient">
                                <img src="{% static 'ladispensa/imgs/index/subtract.svg' %}"
                                width="15" height="15" id="rmv-ingredient">
                            </div>
                            <div class="form-instructions">
                                {% for num, field in form.get_instruction_fields %}
                                <div class="form-instructions__wrapper">
                                    <div>
                                        {{ num }}.
                                    </div>
                                    {{ field }}
                                </div>
                                {% endfor %}
                            </div>
                            <div class="add-form-container">
                                <img src="{% static 'ladispensa/imgs/index/add.svg' %}"
                                width="15" height="15" id="add-instruction">
                                <img src="{% static 'ladispensa/imgs/index/subtract.svg' %}"
                                width="15" height="15" id="rmv-instruction">
                            </div>
                            <input type="submit" class="submit-iteration" value="send">
                        </form>
                    </div>
                </div>
                <div class="recipe-tag toggle-notes">
                    Notes
                </div>
                <div class="recipe-tag toggle-edit">
                    Edit
                </div>
                <div class="recipe-tag toggle-feedback">
                    Feedback
                </div>
            </div>
        </div>
    </div>
<h1>history</h1>
<div class="recipe-history-container"></div>
{% endif %}
{% endblock %}

{% block stylesheet %}
<link href="{% static 'ladispensa/styles/css/test_kitchen.css' %}" rel="stylesheet">
{% endblock %}

{% block script %}
<script src="{% static 'ladispensa/javascript/test_kitchen.js' %}"></script>
{% endblock %}